name: dsc_hacks_technyts
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  cloud_firestore: ^3.4.6
  flutter:
    sdk: flutter
  get: ^4.1.4
  dots_indicator: ^2.1.0
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.1
  curved_navigation_bar: ^1.0.3
  geolocator: ^9.0.1
  geocoder2: ^1.3.0
  webview_flutter: ^3.0.4

dependency_overrides:
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - map_style.json
    - map.jpg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900




  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages